internetarchive/bookreader

BookReaderDemo/index.html
This is the latest version that's working with no modifications
to the bookreader code. Further updates will require some changes.
=> Update jQuery to v1.5.2

BookReader/BookReader.js, BookReader/dragscrollable-br.js, BookReaderDemo/BookReaderJSSimple.js
This is a rebase of pull request #44.
=> Cleanup code with PhpStorm

BookReader/BookReader.js
=> Fix regex issue

BookReader/BookReader.js
Remove the old responsiveAutofit (which is not needed anymore).
=> Add auto mode to 1up autosize (in addition to height and width).

.eslintrc.js, .travis.yml, BookReader/BookReader.js, package-lock.json, package.json
Hi,
So do with this what you want. I just noticed the bookreader doesn't
have eslint set up. This gets BookReader.js passing under eslint.
I've also added a travis.yml file if you want to have travis
automatically check that.
=> Enable eslint, and do some cleanup

BookReader/BookReader.js, BookReader/plugins/plugin.autoplay.js, BookReaderDemo/BookReaderJSAutoplay.js, BookReaderDemo/demo-autoplay.html, BookReaderDemo/index.html, CHANGELOG.md, package-lock.json, package.json, tests/qunit.html, tests/test-plugin-autoplay.js
**Description**
Adds a demo page for the autoplay plugin, adds default values for `flipSpeed` and `flipDelay` rather than use hard-coded values in the autoplay plugin, and adds the ability to pass in override values to the `autoToggle` method. Added QUnit tests.
**Technical**
The version of QUnit being used pointed to a non-existent version of fsevents. Upgraded to the latest version of QUnit, which is now no longer under the package name "qunitjs" but simply "qunit".
**Testing**
Run a local web server and view the demo page at http://localhost:8000/BookReaderDemo/demo-autoplay.html
**Evidence**
=> Adds autoplay demo and default values for flipSpeed and flipDelay

.eslintrc.js, package.json
=> added linter integration into CI

BookReader/BookReader.js, BookReader/plugins/plugin.vendor-fullscreen.js, CHANGELOG.md, README.md, package.json
=> Skips vendor native setup

CHANGELOG.md, package.json
Version bump to 4.2.5 . Do I create a release through the GitHub UI once this is merged, @shaneriley ?
@shaneriley @jbuckner
=> version bump: 4.2.5

BookReader/BookReader.js
=> update version in BookReader.js to 4.2.5

BookReader/BookReader.js
- this will change when we work on page flipping at full screen
=> re-adding click prevention on full screen

.testcaferc.json, package-lock.json, package.json, tests/e2e/README.md, tests/e2e/example.test.js
Please see the README in tests/e2e for instructions.
=> Adds TestCafe dev dependency, instructions, example test

BookReader/BookReader.css, src/css/_BRnav.scss
Fixes https://github.com/internetarchive/bookreader/issues/177
The fix is done by improving the specificity of the CSS rules, and also undoing some rules put in by jQueryUI
=> Bugfix nav styles

BookReaderDemo/BookReaderJSAutoplay.js, BookReaderDemo/BookReaderJSSimple.js
Object.assign doesn't work in ie11!
=> Make demo JS ie11 comptaible

package.json, tests/e2e/autoplay.test.js, tests/e2e/base.test.js, tests/e2e/constants/index.js
=> Adds autoplay e2e tests

tests/e2e/base.test.js
closes #254 
E2E test is passing for both books now.
=> Fix E2E base test

src/js/BookReader.js, tests/plugins/menu_toggle/plugin.menu_toggle.test.js
As requested in https://github.com/internetarchive/bookreader/pull/307
Closes #302
=> Removed Console log in menu_toggle plugin

src/js/BookReader/BookModel.js, src/js/plugins/plugin.search.js
=> Slot resolution

.eslintrc.js, src/js/BookReader.js, src/js/BookReader/BookModel.js, src/js/BookReader/Mode2Up.js, src/js/BookReader/Toolbar/Toolbar.js, src/js/plugins/plugin.print.js, src/js/plugins/plugin.search.js, src/js/plugins/tts/AbstractTTSEngine.js, src/js/plugins/tts/FestivalTTSEngine.js, src/js/plugins/tts/plugin.tts.js, src/js/plugins/tts/utils.js
Fixes #299
Added a new rule in eslintrc.
=> Add space-infix-ops eslint + fix violators

config.yml
Copied the OL config https://github.com/internetarchive/openlibrary/blob/master/.dependabot/config.yml;
here's what it looks like with all the defaults added in:
```yaml
allowed_updates:
- match:
update_type: all
dependency_type: direct
- match:
update_type: security
dependency_type: indirect
automerged_updates: []
default_assignees: []
default_labels:
- 'z: dependencies'
default_reviewers: []
ignored_updates: []
target_branch: master
version_requirement_updates: auto
```
=> Add dependabot config

BookReaderDemo/demo-ia-olivertwist.html, BookReaderDemo/demo-ia-plato.html
These apparently need some SearchInsideAccess.js which is not being imported by the PHP
cc: @iisa
=> Mock SearchInsideAccess to fix IA demos

src/js/BookReader.js
The unbind method was calling jQuery's bind method instead.
=> Fixes unbind method

src/css/BookReader.scss, src/css/_BRnav.scss, src/css/_controls.scss, src/js/BookReader/Navbar/Navbar.js, tests/e2e/models/Navigation.js
=> New chrome adjustments

src/js/plugins/plugin.chapters.js
This was causing a redirect to trigger
=> Fix wrong openlibrary URL

src/css/_BRsearch.scss, src/js/BookReader.js, src/js/plugins/search/view.js
This fixes the issues addressed in https://webarchive.jira.com/browse/WEBDEV-3688. Review app is at https://www-shaner.archive.org/details/goody and test steps are noted in the ticket comments.
=> Search plugin fixes

package.json, src/js/BookReader/Toolbar/Toolbar.js, src/js/plugins/plugin.mobile_nav.js
when book item has inline JS, resulting some popups and alerts execution on bookreader thearter. we want to prevent those alerts by `escapeHTML()` function while render the title in HTML.
https://webarchive.jira.com/browse/WEBDEV-3628
=> webdev-3628 HTML escaping to prevent XSS

.eslintrc.js, src/js/BookReader.js, src/js/BookReader/BookModel.js, src/js/BookReader/Mode2Up.js, src/js/plugins/menu_toggle/plugin.menu_toggle.js, src/js/plugins/plugin.chapters.js, src/js/plugins/plugin.mobile_nav.js, src/js/plugins/plugin.text_selection.js, src/js/plugins/tts/WebTTSEngine.js, tests/BookReader/utils.test.js
=> Added spacing rule

.eslintrc.js, src/js/BookReader.js, src/js/plugins/plugin.chapters.js, src/js/plugins/plugin.mobile_nav.js, src/js/plugins/plugin.text_selection.js, tests/e2e/helpers/mockSearch.js
=> Added space before blocks rule

src/css/_BRmain.scss
No refs to these classes in src
=> Remove old bt CSS

.eslintrc.js
=> Added comma dangle rule in src/js

.eslintrc.js, src/js/plugins/menu_toggle/plugin.menu_toggle.js, src/js/plugins/plugin.archive_analytics.js, src/js/plugins/tts/plugin.tts.js
Fixes #477 
Fixes #478 
Fixes #479 
@cdrini Please have a look. Added all three files. 
The manual fix was required in plugin.menu_toggle.js (line 74)
=> Added files to eslint

src/js/BookReader/Navbar/Navbar.js
Completes [WEBDEV-3847](https://webarchive.jira.com/browse/WEBDEV-3847)
=> Hides directional buttons and shows viewmode buttons on mobile viewports

src/js/plugins/search/plugin.search.js
Adds search term to all of the other Search events.
This supports https://webarchive.jira.com/browse/WEBDEV-3850
=> Bolster search events

src/js/plugins/search/view.js
Fixes [WEBDEV-3879](https://webarchive.jira.com/browse/WEBDEV-3879).
=> Waits to resize until first result flipped to

src/js/plugins/search/view.js
Fixes #505 
single comma message to backticks message to resolve issue
=> rendered message fixed

BookReader/icons/advance.svg, BookReader/icons/review.svg
=> Update advance and review icons

tests/BookReader.options.test.js, tests/BookReader.test.js, tests/BookReader/Mode2Up.test.js, tests/BookReader/Navbar/Navbar.test.js, tests/plugins/menu_toggle/plugin.menu_toggle.test.js, tests/plugins/plugin.autoplay.test.js, tests/plugins/plugin.chapters.test.js, tests/plugins/plugin.mobile_nav.test.js, tests/plugins/plugin.resume.test.js, tests/plugins/plugin.search.test.js, tests/plugins/plugin.text_selection.test.js, tests/plugins/plugin.url.test.js, tests/plugins/plugin.vendor-fullscreen.test.js, tests/plugins/tts/FestivalTTSEngine.test.js
This isn't needed since the tests have an env_setup step.
=> Remove jquery-wrapper import from tests

src/css/_BRnav.scss, src/css/_BRsearch.scss, src/css/_controls.scss, src/js/plugins/search/view.js, tests/plugins/search/plugin.search.test.js, tests/plugins/search/plugin.search.view.test.js
1. always display search results markers (adding them to mobile) - WEBDEV-3921
2. make search results nav tap targets at least 30px by 30px - WEBDEV-3982
3. extend click events
- add new click event to help toggle side menu
- add new test file for Search view
- move search plugin test files to their own directory
- parts of WEBDEV-3981, WEBDEV-3983
=> Search Plugin Updates

src/js/plugins/search/plugin.search.js, src/js/plugins/search/view.js
https://webarchive.jira.com/browse/WEBDEV-3766
=> Suppress framment changeing should be prevent on initial pin click

src/js/BookReader.js, src/js/BookReader/Mode1Up.js, src/js/BookReader/options.js, src/js/plugins/plugin.autoplay.js, tests/BookReader.test.js, tests/BookReader/Mode1Up.test.js
Closes #270 
- Es6ify + add some tests to some zoom related functions
- Pull out Mode1Up into its own file
=> Continuous Zoom Preparatory Refactor

src/js/plugins/tts/plugin.tts.js
https://webarchive.jira.com/browse/WEBDEV-4078
Github issue: https://github.com/internetarchive/bookreader/issues/578
=> Text-to-speech `?_autoReadAloud=auto` param breaking bookreader audio layout

src/js/BookReader.js, src/js/BookReader/options.js, tests/BookReader.options.test.js
- `autoResize = true` by default, sets in-br window change resizer
- `useSrcSet = true` by default, sets srcSets to images
+ move postInit event trigger after `this.init.initComplete = true`
=> initializer updates, new options: `autoResize` && `useSrcSet`

BookReaderDemo/BookReaderDemo.css
Testcafe failing with `AssertionError: expected 800 to deeply equal 1366`
=> Dont limit BR max-width in demo

src/js/plugins/plugin.text_selection.js, tests/plugins/plugin.text_selection.test.js
This was loading twice on init, and multiple times on resize. Let's cache it!
TODO: Add unit test
=> Add cache for text selection page text

src/js/plugins/plugin.text_selection.js, tests/plugins/plugin.text_selection.test.js
Causing pages to crash/freeze up.
Test case: https://archive.org/details/novdec1900images/page/n9/mode/2up
=> Limit words rendered text layer

src/css/_BRnav.scss, src/js/BookReader/Navbar/Navbar.js
=> Removed menu tab at the bottom right

src/js/BookReader.js, src/js/BookReader/BookModel.js, src/js/BookReader/options.js, src/js/BookReader/utils/classes.js, src/js/dragscrollable-br.js, src/js/plugins/plugin.resume.js, src/js/plugins/plugin.text_selection.js, src/js/plugins/tts/AbstractTTSEngine.js, src/js/plugins/tts/WebTTSEngine.js, tests/BookReader/utils/classes.test.js, tests/e2e/helpers/base.js, tests/e2e/helpers/desktopSearch.js, tests/plugins/plugin.print.test.js, tests/plugins/plugin.text_selection.test.js
#682 used https://github.com/codespell-project/codespell to find typos and this PR corrects some of them.
=> Fix typos discovered by codespell in #682

.github/workflows/npm-publish.yml
@cdrini https://github.com/actions/setup-node/releases
=> npm-publish.yml: Upgrade to setup-node/releases@v2

src/css/_BRpages.scss, src/js/BookReader.js, src/js/BookReader/BookModel.js, src/js/BookReader/ImageCache.js, src/js/BookReader/Mode1Up.js, src/js/BookReader/Mode2Up.js, src/js/BookReader/ModeThumb.js, src/js/BookReader/PageContainer.js, src/js/plugins/plugin.text_selection.js, tests/BookReader/BookModel.test.js, tests/BookReader/ImageCache.test.js, tests/BookReader/Mode2Up.test.js, tests/BookReader/PageContainer.test.js, tests/e2e/helpers/base.js, tests/e2e/helpers/rightToLeft.js, tests/e2e/viewmode.test.js, tests/plugins/plugin.text_selection.test.js
For (code) reviewers: Going commit by commit might be best. I tried to leave lots of context in my commit messages :+1:
See it live! https://ia-petabox-drini.archive.org/details/goodytwoshoes00newyiala
https://user-images.githubusercontent.com/6251786/113650258-e8fdbc80-965d-11eb-9950-e687c1e0483f.mp4
https://user-images.githubusercontent.com/6251786/113649551-a1c2fc00-965c-11eb-98da-e983079e67d3.mp4
Todo:
- Did some basic tests and it seems like it's making the same number of requests as before. Didn't test super thoroughly though.
Todo in future PR:
- Limit the cache to powers of 2; that'll result in more cache hits.
=> PageContainer + dual image resolution loading

src/js/BookReader.js
https://webarchive.jira.com/browse/WEBDEV-4130
=> Copy paste URL in browser should preserve /search params

.github/workflows/npm-publish.yml
Tried generating an "automatic" CI key; hopefully that'll fix it.
=> Revert publish-npm attempted fix

package.json
Noticed a lot of the files that were claimed to be deleted were still there!
=> build should start from clean directory

src/js/plugins/search/plugin.search.js
They need to take into account PPI now!
=> Fix search results not positioned correctly Mode1Up

package-lock.json, package.json
npm i --save-dev concurrently@latest \
http-server@latest \
live-server@latest \
node-fetch@latest
concurrently was the only one with updates.
=> Update dev-flow dependencies

src/BookReaderComponent/BookReaderComponent.js
=> remove full browser width from web components wrapper

package-lock.json, package.json
Some changes in file output sizes, but nothing drastic.
```
BookReader/BookReader.js                           | Bin 240292 -> 245512 bytes
BookReader/BookReader.js.map                       | Bin 909518 -> 937841 bytes
BookReader/bookreader-component-bundle.js          | Bin 242425 -> 244397 bytes
BookReader/bookreader-component-bundle.js.map      | Bin 531750 -> 540334 bytes
BookReader/icons/advance.svg                       | Bin 465 -> 493 bytes
BookReader/icons/chevron-right.svg                 | Bin 332 -> 340 bytes
BookReader/icons/close-circle.svg                  | Bin 337 -> 347 bytes
BookReader/icons/left-arrow.svg                    | Bin 180 -> 180 bytes
BookReader/icons/magnify-minus.svg                 | Bin 375 -> 375 bytes
BookReader/icons/magnify-plus.svg …
```
=> Update build dependencies

.gitignore, src/BookNavigator/BookNavigator.js, src/BookNavigator/bookmarks/bookmark-edit.js, src/BookNavigator/bookmarks/bookmarks-provider.js, src/BookNavigator/bookmarks/ia-bookmarks.js
**Problem:**
- add access and integrate bookmarks provider inside menu panel
- check if a user is signed in to load the bookmarks list saved 
**Solution:**
- add/link up BookmarkProvider in BookNavigator
- if a user is signed in, load bookmarks saved on a specific page of the book
**Testing Steps:**
- load a book
- access the side menu panel 
- check if Bookmarks option is displayed
- click Bookmarks option
- login layout will be displayed if user is not signed in
- otherwise, it will display the bookmarks list layout
----
_gif layout to follow_
=> Add bookmark feature to check if user is signedIn

package-lock.json, package.json
version bump menu slider to updated configuration
To test: go to - https://deploy-preview-787--lucid-poitras-9a1249.netlify.app/bookreaderdemo/demo-internetarchive?ocaid=theworksofplato01platiala
toggle side menu -> closes & opens successfully
=> bump menu slider

src/BookNavigator/assets/button-base.js, src/BookNavigator/bookmarks/bookmarks-loginCTA.js, src/BookNavigator/downloads/downloads.js
https://webarchive.jira.com/browse/WEBDEV-4474
=> Update download button styling for book navigator

src/BookNavigator/volumes/volumes-provider.js
- no need for instance flag at initial sort
- icon logic reset
=> volumes, simplify sort flow

.eslintrc.js, src/BookReader.js, src/BookReader/DebugConsole.js, src/BookReader/Toolbar/Toolbar.js, src/plugins/plugin.chapters.js, src/plugins/plugin.mobile_nav.js, src/plugins/plugin.vendor-fullscreen.js, src/plugins/search/view.js, src/plugins/tts/plugin.tts.js, tests/BookReader/Navbar/Navbar.test.js, tests/plugins/plugin.mobile_nav.test.js, tests/plugins/plugin.text_selection.test.js
Closes #845
Fixes all the "warning" jquery eslints, and makes them now trigger eslint errors, to avoid them coming back!
=> Fix eslint jquery warnings

src/BookNavigator/visual-adjustments/visual-adjustments-provider.js
Solution summary:
- make zoom out parameter explicit -1
- removed to refactor to separate PR
WEBDEV-4797
=> Fix BookNavigator zoom out in thumbnail view

src/BookReader.js, src/BookReader/Mode1Up.js, src/BookReader/ModeThumb.js, src/BookReader/options.js, tests/jest/BookReader/ModeThumb.test.js
=> Refactor zoom code to string params, add modeThumb test

BookReader/BookReader.css, src/css/_controls.scss
https://webarchive.jira.com/browse/WEBDEV-4751
=> Read aloud play/pause button cut-off on safari v 15

src/plugins/url/UrlPlugin.js, tests/jest/plugins/url/UrlPlugin.test.js
- remove default state setting in URL 
- remove trailing slashes being added in the URL
=> Remove default state and update tests

src/BookNavigator/bookmarks/bookmarks-provider.js, src/BookNavigator/bookmarks/ia-bookmarks.js, tests/karma/BookNavigator/bookmarks/ia-bookmarks.test.js
Problem: dynamic demo update did not fetch patron bookmarks.
Solution: add fetch when starting up
Testing:
- go to demo: https://deploy-preview-922--lucid-poitras-9a1249.netlify.app/
- open dev tools
- toggle "Logged In state"
- ✅  api calls fire (and fail in demo) for patron bookmarks
=> fetch those bookmarks

.eslintrc.js, src/BookReader.js
Closes #937 
- remove overrides block from .eslintrc.js
- ran `npx eslint --fix src/BookReader.js` after removing the overrides block
- changed `var` to `let` or `const` where needed
=> remove overrides block and changed var to let and const

.testcaferc.js, tests/e2e/base.test.js, tests/e2e/helpers/params.js, tests/e2e/viewmode.test.js
Closes #945
updates test cafe so that e2e tests run.
=> Testcafe run

src/BookNavigator/bookmarks/ia-bookmarks.js, src/plugins/tts/AbstractTTSEngine.js, src/plugins/tts/PageChunkIterator.js, src/plugins/tts/WebTTSEngine.js
Work toward #940
Code Review: 
- Need Heavy Code Review, if the logic has been transferred correctly
Style: 
- Ran `npx eslint .`  to make sure the styling is correct.
=> update to async await

src/plugins/plugin.chapters.js, src/plugins/search/plugin.search.js, src/plugins/tts/PageChunk.js
issue #940 
Need review on the changes. Please let me know the issues in the changes and I'll fix them.
=> update .then() to async/await

.github/workflows/node.js.yml, .github/workflows/npm-publish.yml, package-lock.json, tests/jest/plugins/plugin.text_selection.test.js
* Updates .github/workflow `yml` files
* Updates `package-lock.json`
Running `npm install` locally doesn't seem to cause any test failures when running
`npx jest`.
Fixes #938
=> Update Node.js v16.x

src/plugins/plugin.text_selection.js, src/plugins/tts/FestivalTTSEngine.js, tests/jest/plugins/search/plugin.search.test.js, tests/jest/plugins/tts/AbstractTTSEngine.test.js
work on #940 
need heavy review.
=> update async await remaining

src/BookNavigator/bookmarks/ia-bookmarks.js, src/plugins/tts/WebTTSEngine.js
=> update remaining async/await

package-lock.json, package.json
testing: go to review app https://deploy-preview-963--lucid-poitras-9a1249.netlify.app/bookreaderdemo/demo-internetarchive?ocaid=theworksofplato01platiala -> go to share menu panel -> all icons are there ✅ , clicking on it goes to share that particular type
=> sharing options menu at lit2

src/plugins/tts/AbstractTTSEngine.js
MS Edge seems to fire the `voiceschanged` event a lot; causing it to reset the voice. So only switch to "Best" voice if user hasn't explicitly selected a voice.
=> Fix MS Edge voice selection not sticking

src/BookNavigator/search/a-search-result.js, src/plugins/search/plugin.search.js, src/plugins/search/view.js, tests/jest/plugins/search/plugin.search.test.js, tests/karma/BookNavigator/search/search-results.test.js
The numbers were incorrect for some reason. Change them to be consistent with the numbers on the search pins. Still not fully consistent with e.g. slider, but we can solve that another day. They are at least not wildly incorrect now.
| Before | After |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/6251786/161102395-a5638c91-b85c-4bdc-a3cc-f682df9d42d2.png) | ![image](https://user-images.githubusercontent.com/6251786/161102456-5deeff78-2240-4f66-9597-bb63463ec243.png) |
=> Fix page number wrong in sidepanel

renovate.json
CC @iisa it wasn't working :/ 
https://github.com/internetarchive/bookreader/pull/1028
Let's try this?
=> Try to fix GHA renovate pattern

package.json, tests/jest/BookNavigator/search/search-provider.test.js, tests/jest/BookNavigator/search/search-results.test.js
Proof-of-concept to see how hard it is and to create some templates. Going to then create issues for the rest of the files :+1:
Everything worked smoothly! Just a few config changes.
=> Convert 2 tests from karma to jest

BookReaderDemo/IADemoBr.js
Remove BRJSLocate call and hit BookReaderJSIA.php directly. It seems like JSLocate was creating the wrong manifest URL!
=> Fix dev environment failing to load some books

package.json, src/BookReader.js, src/BookReader/events.js
https://webarchive.jira.com/browse/WEBDEV-5711
Description: ia-book-actions uses new feature call `loan-auto-renew` where we need to send a specific pageChanged event when user clicked on new page.
=> Dispatch custom event from bookreader for ia-book-actions

src/BookReader.js, src/BookReader/options.js, tests/jest/BookReader.test.js
Refactor these functions to be easier to read/less verbose.
=> Refactor/cleanup overrideDefaultMode

package-lock.json, package.json
Update to latest to avoid duplicate inserts on prod.
=> Update some ia packages

src/css/_icons.scss
=> Fix incorrect filename in _icons.scss

src/plugins/url/UrlPlugin.js, src/plugins/url/plugin.url.js, tests/jest/plugins/url/plugin.url.test.js
Closes #1170 
Happens when calling history.replaceState
=> Fix DOMException in sandboxed iframe in chrome

src/BookReader/Mode1Up.js
=> Call updateVisibleRegion after the UI has rendered

src/plugins/search/plugin.search.js
=> Fix mode2up preview pages hanging

src/BookReader/BookModel.js, tests/jest/BookReader/BookModel.test.js
Testing: https://www-drini.archive.org/details/micro_IAMFTEST00_0022/page/60/mode/1up now works
=> Avoid ppi<10 causing UI to break

src/BookReader.js, src/plugins/url/UrlPlugin.js, tests/jest/plugins/url/UrlPlugin.test.js
New page number detection logic now supports more complicated page numbers, which might require encoding! So add support for that.
=> Encode page number in url

src/plugins/tts/AbstractTTSEngine.js, src/plugins/tts/utils.js
Tested:
- works in embedded iframe w sandboxing
- ReadAloud voice remembering works
=> Fix error with localStorage in sandboxed iframe

BookReaderDemo/BookReaderDemo.css
=> fix:Some demos not working.

package-lock.json, package.json
https://webarchive.jira.com/browse/WEBDEV-6544
=> Firefox not scrolling to selected volume in the volume side panel

package-lock.json, package.json
Updates going out:
- https://github.com/internetarchive/iaux-item-navigator/pull/16
- https://github.com/internetarchive/iaux-item-navigator/pull/18
=> @internetarchive/ia-item-navigator@2.1.2

.github/workflows/node.js.yml, package-lock.json, package.json, renovate.json
Shout out to @latonv for finding the fix!
=> Replace deprecated codecov npm package with github action

src/plugins/plugin.iiif.js
=> Fix IIIF plugin missing last page + erroring when metadata unspecified

src/BookNavigator/downloads/downloads.js
Removes outdated Aldiko + SimplyE links and clarifies text re: Thorium. Also makes variable name less brittle.
=> WEBDEV-7126 Revise LCP download message

src/BookNavigator/downloads/downloads.js
Adds Cantook for iOS and Android to LCP download message.
=> WEBDEV-7126 Add mobile options to LCP download message

src/plugins/plugin.text_selection.js, src/plugins/search/plugin.search.js, src/plugins/tts/PageChunk.js, tests/jest/plugins/plugin.text_selection.test.js
Tested Search Inside, Read Aloud, text selection all worked for public books in the netlify test environment.
=> Pass forward credentials for protected books

src/plugins/tts/AbstractTTSEngine.js, src/plugins/tts/FestivalTTSEngine.js, src/plugins/tts/plugin.tts.js
Addendum to #1376 
To specify the URL of the remote TTS service
=> Refactor out new TTS option, remoteTtsUrl -- fix festival not working

src/plugins/plugin.chapters.js
And rename some of the options -- with backwards compatibility.
=> Add option to ChaptersPlugin for explicit openLibraryId

src/plugins/tts/plugin.tts.js
=> Fix TTS scrolling to top of page unexpectedly

src/BookNavigator/search/search-provider.js, src/BookReader.js, src/BookReader/Toolbar/Toolbar.js, src/plugins/plugin.text_selection.js, src/plugins/search/view.js, src/plugins/tts/plugin.tts.js, src/plugins/url/plugin.url.js, tests/e2e/helpers/base.js, tests/jest/BookNavigator/search/search-provider.test.js, tests/jest/BookReader.test.js, tests/jest/plugins/plugin.autoplay.test.js, tests/jest/plugins/plugin.resume.test.js, tests/jest/plugins/plugin.text_selection.test.js, tests/jest/plugins/search/plugin.search.test.js, tests/jest/plugins/search/plugin.search.view.test.js
Preparatory refactor for #1399 .
=> Move BookReader._plugins -> BookReader.plugins , making it public

src/BookReader.js, src/BookReader/Navbar/Navbar.js, src/css/_BRnav.scss, src/css/_BRsearch.scss
And remove some dead code from the control show/hide button ( 🥲 )
=> Move bindNavigationHandlers into Navbar

src/BookReader/Mode1UpLit.js, src/BookReader/Mode2UpLit.js, src/css/_TextSelection.scss, src/plugins/translate/plugin.translate.js
Various QoL changes for display/fit
- Add lang to BRtranslateLayer
- Long hover over translated paragraph elements show scanned book image
- Enabled text selection for paragraph only
- Adjust font-size for visible page translated text paragraphs to prevent text overflow
- Minor styling changes throughout
=> Translation Plugin QoL and Display improvements 
