BookReader/BookReader.js, BookReader/plugins/plugin.url.js, CHANGELOG.md, package.json
When the view changes, a bookreader event fires which tracks download counts for the book. We'd also like to track view changes as a separate analytics "event". This PR adds the additional call.
=> Add additional tracking event when view changes.

BookReader/BookReader.css, src/css/_MobileNav.scss
Closes #98 
The root issue is that the SVG is not displaying (for some reason), but for now we show the PNG by default instead.
**NOTE** I don't have a local copy of this running, so didn't try building/compiling it or anything. Just made the changes directly. Here's the before/after from applying the changes in devtools:
| Before | After |
|---|---|
| ![image](https://user-images.githubusercontent.com/6251786/56689738-c7da7600-66a9-11e9-96ad-e1d9f185a214.png) | ![image](https://user-images.githubusercontent.com/6251786/56689764-d58ffb80-66a9-11e9-8897-b08763ca28d5.png) |
=> hotfix: hamburger icon invisible on mobile

BookReader/BookReader.js, tests/qunit.html, tests/test-bookreader.js
There is a bug in the archive.org `/stream` view where after a user selects a page from the thumbnail view, the page starts rapidly switching between the thumbnail view and the full page view, causing the browser to freeze.
Click on a thumbnail to reproduce
Bug: https://archive.org/stream/goodytwoshoes00newyiala#mode/thumb
Fix: https://ia-petabox-review-jasonb-boo-u4y32j.archive.org/stream/goodytwoshoes00newyiala#page/n8/mode/thumb
There were two calls being made `trigger(BookReader.eventNames.fragmentChange)`, one in `updateFirstIndex()` and another in `switchMode()`. This was triggering other listeners that kept calling back into `switchMode()` and we'd get caught in the loop.
This adds a parameter to suppress the `trigger` calls so we can make both of the calls first, then call …
=> WEBDEV-1992: Fix Rapid Reload Bug in archive.org `/stream` View

package-lock.json
We got a notification from Github that our version of `js-yaml` has a security vulnerability. Thisbumps it up to the current (fixed) version.
=> Update js-yaml to Current Version

BookReader/BookReader.css, src/css/_MobileNav.scss
Fixes #100 
With PNG hamburger:
With CSS hamburger:
=> Replaces hamburger image icon with CSS

BookReader/BookReader.js, package-lock.json, package.json, src/js/plugins/tts/AbstractTTSEngine.js, src/js/plugins/tts/plugin.tts.js, src/js/plugins/tts/utils.js, tests/plugins/tts/utils.test.js
Add a `bookLanguage` option to book reader that we can use for TTS. This has corresponding changes to petabox to _provide_ the language, which will go out once this is merged ( https://git.archive.org/ia/petabox/tree/131-bookreader-book-lang ).
Closes #131 
- It's often ISO 639-2/B, but can be anything
- See `toISO6391`
- Added another dependency.
- The `toISO6391` function is purposefully not very performant; it'll only get run once per page load, so I opted for an algorithm that requires the data to be in as condensed a format as possible.
- It feels a little wrong to be doing this here? I think it would more appropriate for the `toISO6391` function to be inside petabox, so it does the data wrangling before providing the language to the bookreader.
@jbuckner @mekarpeles
=> Get book's language as ISO 639-1

BookReader/plugins/plugin.search.js
Add custom event listener to new ambient event `BookReader:navToggled`
where the pins hide when the menu hides
Please note that this compounds on the latest menu toggle #171 & zoom click #172 fixes
https://webarchive.jira.com/browse/WEBDEV-2736
Evidence:
=> Plugin, search: hide search results pins when menu toggles

BookReader/BookReader.js
Pressing -/= or numpad -/+ will now zoom out/in. We already support left/right/pgup/pgdown/home/end, so this seems fine.
=> add keyboard hooks for zoom in/out

BookReader/BookReader.js, BookReaderDemo/index.html, BookReaderDemo/view_mode.html
Closes #195 
This allows for the `mode` property on the supplied options to be used to override the initial mode. Added a page with a demo and comment in the demo's code indicating where the mode values can be found. Currently, you can use class properties `constMode1up`, `constMode2up`, and `constModeThumb`.
=> Enables initial view mode to be defined

BookReader/BookReader.js
This PR is based on https://webarchive.jira.com/browse/WEBDEV-2737
- When you have zoomed-in 2 page view, should be be able to drag image to see around.
- When you have zoomed-in 2 page view, you should be able to click on book image to change page.
=> BookReader: zoomed-in 2 page view, clicking page does not change the page

BookReader/BookReader.js
This PR is based of https://webarchive.jira.com/browse/WEBDEV-2995
- Currently on this page https://archive.org/details/goody/mode/1up you **can't** drag image to see next 
page. Either you can scroll the page using mouse wheel or flip right and/or flit left.
- Same behaviour is applied on liner notes.
=> Mouse drag of image inconsistent for onepage view

BookReader/BookReader.css, src/css/_MobileNav.scss
Closes #144 
Reverts internetarchive/bookreader#106 ; it was causing an odd issue where the button would only work if clicked on the hamburger buns or patty :P Choosing a revert here since it seems like the least likely change to cause more bugs (the fact that it requires very little work, is also appealing :P ). We can find a longer-term solution in the future.
✅ Tested: FF73; Ch 80 on Win10
Steps:
1. Visit http://localhost:8000/BookReaderDemo/demo-fullscreen.html#mode/2up
2. Resize until in mobile view
3. Click hamburger icon
=> Switch back to using PNG for hamburger icon

package.json, tests/e2e/base.test.js, tests/e2e/example.test.js
- Adds a new command in `package.json` to keep test server on locally
- Adds tests for:
- On load view expectations
- Full sized BookReader Nav expectations
- pull down branch
- make sure you have a fresh new module directory `npm install`
- run demo server
- see: https://github.com/internetarchive/bookreader/blob/master/README.md#demos
- run command: `npm run test:e2e`
- tests run successfully
- run command `npm run test:e2e:dev`
- tests run and test server continues to listen for file changes
This is for internal ticket: https://webarchive.jira.com/browse/WEBDEV-3159
=> Extend end to end tests in Test Cafe

webpack.config.js
Takes a file from the file list and outputs compiled file in the `BookReader` directory.
It keeps the same flattened directory structure as the file mapper it replaces.
Note: I purposely kept the file list, and didn't fully automate because I wanted to make the entrypoints explicit.
This is part of internal ticket: https://webarchive.jira.com/browse/WEBDEV-3183
Regex example: https://regexr.com/4v9m4
- pull down branch
- at top of BookReader directory, run the following:
- `npm install` to update your modules
- `npx webpack` to build the files
- if you didn't delete any built files or update an es6 file listed, no files should have updated
- if you update a file and run `npx webpack` - a change should be picked up by git for you to commit/review
=> Update webpack to dynamically compile files from a list

README.md
Since we need to include the build files in the repo to maintain backwards compatibility.
=> Add build instruction to README

.travis.yml
Per https://github.com/DevExpress/testcafe/pull/4828/commits/8fdedc9a58e99972a05ff7c54cd04a851dabbec8
adds a `before_script` block
=> Removes xvfb-run command in front of e2e test script

.gitattributes
This way CSS changes don't show up twice when running `git diff`.
=> Treat CSS build files as binary

.travis.yml, README.md
Run the build step inside Travis to ensure the tests are running on the latest code. This means we no longer need to include the build files in PRs \o/ . The build files will only be added when a release is cut (automatically by the release script).
Note: If you're testing this on a review app or something, you'll now have to run `npm build` on the review app.
=> Run build in Travis

package.json, scripts/preversion.js
The preversion script (run before a version bump happens) outputs a github link to a diff of that last version up to master. This is useful, but also a little too much information. Changing it to provide a link to the PRs that were merged since then.
Before:
> Here's what's changed since the last version: [https://github.com/internetarchive/bookreader/compare/v4.8.0...master](https://github.com/internetarchive/bookreader/compare/v4.8.0...master)
After: 
> Here are all the PRs that were merged since the last version: https://github.com/internetarchive/bookreader/pulls?q=is%3Apr+is%3Amerged+merged%3A2020-04-14T15%3A40%3A13Z..2020-05-07T21%3A24%3A05Z+sort%3Aupdated-asc
=> Make preversion script output link of new PRs instead of new commits

tests/BookReader/Mode2Up.test.js, tests/BookReader/Toolbar/Toolbar.test.js
Created an empty implementation of window.open to suppress the error.
Closes https://github.com/internetarchive/bookreader/issues/303
=> Trying to supress the error

src/js/BookReader/Mode2Up.js, tests/BookReader/Mode2Up.test.js
Problem: 
Go to https://archive.org/details/sim_the-bibliotheca-sacra_1905-04_62_246/page/334/mode/2up/search/Egyptian+sacrifices - and the search result on the page you landed on does not have highlight.
If you flip forward and then back, the highlight is there.
This fixes the problem.
Go to: https://www-isa.archive.org/details/newatlantis642baco/page/42/mode/2up/search/atlantis
and the result is highlighted on load ✅ 
To test locally:
- checkout branch
- update your dependencies, cmd: `npm install`
- run your dev server, cmd: `npm run serve-dev`
- go to `http://127.0.0.1:8080/BookReaderDemo/demo-ia-plato.html#page/388/mode/2up/search/honest` - and you will see the result highlighted on the page you dropped into
=> Search result is now highlighted when user lands on this page

src/js/plugins/plugin.mobile_nav.js, src/js/plugins/plugin.search.js
**1) search term highlight does not show when the page is unviewable**
- Go to: https://www-isa.archive.org/details/goldengalleonsof0000grah
- inside book search, input & initiate search for: `island`
- pins drop -> click around -> ...
- ... -> if page is viewable, search is highlighted
- ... -> if page isn't viewable, "try again later" placeholder is visible with no highlight
**2) Both mobile & desktop search inputs sync in value on search term change**
- Go to: https://www-isa.archive.org/details/goldengalleonsof0000grah
- inside book search, input & initiate search for: `island`
- shrink viewport width until it's in mobile view
- open menu 🍔  -> then click `Search` panel
- In search term form, input & initiate on term `shipwreck`
- no results, cool
- grow viewport width until it is …
=> Search inside cleanup

BookReaderDemo/immersion-1up.html, BookReaderDemo/index.html, src/js/BookReader.js, src/js/BookReader/options.js
This fixes an issue where fullscreen was started before the pages were initially resized to fit the BookReader container and a corresponding class was removed to display the images. A new demo page was added to illustrate the ability to enable fullscreen mode on init for items that start in a mode other than 2up.
=> Start fullscreen post resize

src/js/BookReader.js, src/js/BookReader/Mode2Up.js, tests/BookReader/Mode2Up.test.js
Previously, it would prefetch the unviewable pages as well (as in the dummy page; not the actual uri). Now it only prefetches the first unviewable, and then everything else. Also moved this function to Mode2Up, since it's only used there.
=> Prefetch should skip unviewable pages

package.json
Closes #312 
This was failing in Windows. Note this will likely still fail in windows without a bash client (might need something like cross-env if we want to support that use case).
Src: https://stackoverflow.com/a/27090755/2317712
Testing:
- `npm run test:e2e` starts testcafe (Windows + git bash)
=> Use env to set environment variables in package.json

src/js/plugins/plugin.url.js
The issue was caused by a bad comparison of the oldLocationHash not
including the newQueryString for comparison. This led to the
(newFragment != this.oldLocationHash) test failing after the page
had been traversed to.
=> Fixes #349 BookReader flipping randomly goes wonky

webpack.config.js
We'd over-abstracted this; we can just use a basic setup :)
This will also make it easier to dedupe the shared code inside BookReader once we go to webpack 5 (still in beta :( )! https://webpack.js.org/configuration/entry-context/#dependencies
=> Refactor: simpler webpack.config.js

src/js/BookReader/BookModel.js
This issue was fixed by returning fallback value if index is invalid in `_getDataProp `function.
Also affected `/demo-plugin-menu-toggle.html` and `/demo-advanced.html`.
closes #358
=> Fixed advanced demo not turning pages

src/js/plugins/plugin.url.js
Previous fix involving `plugin.url.js` was not working anymore in URL hash mode due to changes to `urlUpdateFragment` made in the generic demo feature.
Changed this.oldLocationHash to use newQueryStringSearch instead of newQueryString in url hash mode.
closes #349
=> Fix random page flipping

src/js/BookReader.js, tests/BookReader.test.js
Fixes high resolution displays having blurry images using the HTML srcset property for img elements. The srcset is applied to the bookreader page images so that for each available image, with higher resolution than the one selected by default, there is a corresponding 2x, 4x, 8x or higher attribute.
closes #372
=> Fix high resolution displays having blurry images

src/js/BookReader.js, tests/BookReader/BookReaderPublicFunctions.test.js
Problem: BookReader jQuery `trigger` events can only be listened to by jQuery.
Solution: This extends `br.trigger` to always throw a custom event.
Testing
- go to: https://deploy-preview-423--lucid-poitras-9a1249.netlify.app/bookreaderdemo/demo-internetarchive?ocaid=adventuresofoli00dick
- open dev console
- go to console tab/drawer
- add this function into the console drawer: window.addEventListener('BookReader:fullscreenToggled', (e) => { console.log('successfully caught event', e) });
- click Fullscreen on bookreader
- you see the console output. yay
=> Emit custom event to trigger

.travis.yml
Looks like I forgot master is also a branch :D 
I enabled "build on pushed branches" in https://travis-ci.com/github/internetarchive/bookreader/settings, and set it to only build master via .travis.yml
=> Run travis on master branch pushes!

package-lock.json, package.json, src/js/BookReader.js, webpack.config.js
Upgrade to webpack 5 (still in beta 😬 ) But we dropped our total prod file size by 46% ! Namely through duplicate code removal.
File | master | webpack 5 | Change
-- | -- | -- | --
BookReader/BookReader.js | 163,654 | 165,499 | 1.13%
BookReader/plugins/plugin.archive_analytics.js | 14,154 | 2,209 | -84.39%
BookReader/plugins/plugin.autoplay.js | 13,742 | 2,067 | -84.96%
BookReader/plugins/plugin.chapters.js | 18,342 | 4,503 | -75.45%
BookReader/plugins/plugin.iframe.js | 1,573 | 700 | -55.50%
BookReader/plugins/plugin.menu_toggle.js | 11,077 | 2,609 | -76.45%
BookReader/plugins/plugin.mobile_nav.js | 26,924 | 6,331 | -76.49%
BookReader/plugins/plugin.print.js | 17,892 | 3,457 | -80.68%
BookReader/plugins/plugin.resume.js | 17,965 | 3,486 | -80.60%
BookReader/plugins/plugin.search.js | …
=> Upgrade to Webpack 5 - reduce prod size 46%!

src/js/BookReader.js, src/js/BookReader/utils.js, tests/BookReader/utils.test.js
This was causing IE11 to brick. Apparently not supported by core-js :(
https://github.com/zloirock/core-js/issues/354
=> Fix: Polyfill CustomEvent constructor

src/js/plugins/plugin.text_selection.js, src/js/plugins/tts/WebTTSEngine.js, src/js/plugins/tts/utils.js, src/util/browserSniffing.js, tests/plugins/tts/utils.test.js, tests/util/browserSniffing.test.js
Where to begin. So the way this works, is the svg text layer has `pointer-events: none` (so that you can right click on non-text and access image options). The word elements (usually `<tspan>`) override this with `pointer-events: all`, so that you can have the cursor hover effect, and so the event listeners work. The problem is that for some reason, on Safari, the `pointer-events: all` override wasn't working on `<tspan>` elements. So the solution I ended up with was on Safari, apply that override on the _paragraph_ element. This has some problems, in that it makes it a little more difficult to pan when in 2up zoomed-in, but should otherwise be fine.
Other things I tried:
- Using `<text>` for the word instead of `<tspan>` (as we do on Firefox). We can't do this on Chrome/Safari, because …
=> Fix text selection on Safari

src/js/plugins/search/plugin.search.js, src/js/plugins/search/view.js
The search plugin's `setup` method is being called twice, causing two instances of the search views to be created. This checks for the existence of a search view and skips creating a new instance, while also adding a call to teardown the search navigation when search results are returned to ensure one search navigation is being rendered for search results.
Testing steps and review app can be found in [WEBDEV-3832](https://webarchive.jira.com/browse/WEBDEV-3832)
=> Skips subsequent creation of search views when setup called 1+n times

src/js/BookReader.js
Since 2up mode page containers are in reverse DOM order when flipping pages forward, there is no accurate method of determining which container is the left positioned container and which is right. This adds a data attribute based on the leaf data to determine which side the container is positioned on.
=> Adds data attribute to 2up page containers for side designation

src/js/BookReader.js
When we need to start the bookreader in fullscreen, we need to pass it through the fullscreen toggler so we can fire the event for the item & book navigators to respond appropriately.
Testing: 
go to https://www-isa.archive.org/details/fivehundredpoint08tussuoft/page/n5/mode/2up?q=fasdfioawer&view=theater -> bookreader opens fullscreen, in-browser
=> use fullscreen toggle flow to fire event

src/js/BookReader.js, tests/BookReader/BookReaderPublicFunctions.test.js
Problem: starting 1up mode in fullscreen did not start at the requested page.
- while the outer bookreader container changes size to fullscreen, somewhere in the `resize` chain changes the page.
- pin current index at start of fullscreen toggle
- **then** set it after entrance animation, so that the bookreader's containers are already enlarged.
- this prevents extra calls that change the page due to resizing functionality
- added a boolean to whether or not we set the keyboard Fullscreen Escape shortcut: `bindKeyboardControls`
- this is to accommodate /stream page's basic default fullscreen view (they never leave it)
- /stream page will now use main fullscreen toggle fn: `br.toggleFullscreen` to initiate Fullscreen instead of doing a work around
- some code rearrangement, to move the ESC …
=> Fix 1up fullscreen loading

src/css/_controls.scss
Closes #507
- Change background color to controlsBG to match the rest of the controls UI
=> Text Speed selector has white text on white on Chrome #507

src/css/_MobileNav.scss
Closes #514
Changing color of .chapter-clickable to white as other text in table of contents.
=> fix: table of contents black text on black 

webpack.config.js
dependOn let's webpack include code/polyfills in shared nodes of the dependency tree. But since a client (and in fact IA) might be using its own copy of jquery, this was causing colorbox to break when integrated into IA.
This causes a small jump in file size--and a peculiarly large jump in file size to jquery.browser.min.js 3KB -> 98KB! So I disabled it for this one and will confirm that it is still working correctly on IA.
This won't matter once we import most of these via JS.
=> Remove dependOn for jquery and friends

index.html, src/css/_controls.scss, src/js/plugins/tts/plugin.tts.js
When focus is given to the search input in the top right of BookReader and tab is pressed twice, the contents of the book container are shifted upward to show the TTS toolbar offscreen. This hides the TTS toolbar when not active, preventing the controls from being part of the tab index. In order to both toggle display and animate position in and out, timeouts are employed to toggle the animation shortly after visibility is given and visibility is removed immediately after the animation out is completed.
=> Remove exit animation TTS toolbar

BookReaderDemo/demo-internetarchive.html, src/js/plugins/plugin.text_selection.js, tests/plugins/plugin.text_selection.test.js
Fix:
- Defining both full djvu xml url and single page djvu xml url causes neither to work; broke textsel on netlify
- No longer need options overrides now text sel is in prod
- Avoid requests for special index=-1 cover; causing a bunch of errors in Sentry
=> Fix some text selection issues

package.json
Was getting some odd errors when using jest; I think it was using a version available to the system, as opposed to the one installed in node_modules, perhaps causing the errors.
=> Use npx for scripts to ensure run with correct versions

src/js/plugins/plugin.text_selection.js, tests/plugins/plugin.text_selection.test.js
Some items do not have a dejavu.xml, and when that happens, the xml parser borks inside of promise chain.
- go to: https://archive.org/stream/EQuran00003/E-Quran-00003#page/n54/mode/1up
- open console - you see lots of errors
- wrap response in a try/catch to parse incoming XML
Go to: https://www-isa2.archive.org/stream/EQuran00003/E-Quran-00003#page/n54/mode/1up
Error no longer happens in console
Go to a book that has dejavu.xml available:
- https://www-isa2.archive.org/stream/goody#page/n22/mode/1up
- you can select text
=> Update Text selection error handling to handle empty xml file

src/js/BookReader/Navbar/Navbar.js, tests/BookReader/Navbar/Navbar.test.js
- go to an asserted page: `https://deploy-preview-558--lucid-poitras-9a1249.netlify.app/bookreaderdemo/demo-internetarchive?ocaid=goody#page/48/mode/2up` => page label in nav: `Page 48 of 156`
- go to a non-asserted page: `https://deploy-preview-558--lucid-poitras-9a1249.netlify.app/bookreaderdemo/demo-internetarchive?ocaid=B-001-014-456#page/n75/mode/2up` => page label in nav: `Page (76 of 132)`
https://webarchive.jira.com/browse/WEBDEV-4017
=> update non-asserted page labelling next to nav scrubber

package.json, webpack.config.js
- Use webpack dev mode for dev server
- Make live-server only watch the files it needs to watch
- Make webpack ignore built files
- Speed up jest --watch by making it only watch src/tests dirs (My VSCode jest extension no longer crashes!)
Making a JS change went from ~10-20s to cause a refresh to ~600ms :)
=> Faster serve dev (>10x!)

src/js/BookReader.js, src/js/BookReader/Mode2Up.js
Problem:
If container DOM is not set, the reduction factors of 2up mode are calculating against `NaN` and breaks all the things.
Solution:
- remove redundant `this.reduce` calculation
- pass `this.reduce` through to image url creation.
To Test: go to www-isa.archive.org/details/goody
open dev tools
refresh
look at BookReaderImages.php requests
confirm that the URL does not have scale=1
=> 2up draw - reduction factors + making sure actual numbers are used when calculating

src/js/BookReader/Mode1Up.js
To test - use incognito window:
1. go to `www-isa2.archive.org/stream/goody?ref=ol`
2. open inspector
3. go to 1up mode
4. look at image element, note srcSet is empty (like in pic)
5. go to `www-isa2.archive.org/details/goody/mode/1up`
6. steps 2 - 4 => no srcSet either.
=> add srcSet option to 1up

src/js/BookReader.js
Problem: even if 2up is not available, when exiting fullscreen, bookreader will put book at 2up mode
Solution: check to see if 2up mode is available before switching modes
=> exit fullscreen - switch to 2up if available

src/js/BookReader.js, src/js/BookReader/Mode2Up.js, tests/BookReader/Mode2Up.test.js
Goal: During resize: only resize the 2up spread IF the next-calculated reduction factor is the same or "worse" than the images that have already been drawn.
Dev notes:
- parse out in-line style generation to be reused during redraw & resizing
- add check to confirm if one should redraw or resize
- add bypass so that it always redraws when zooming
`https://webarchive.jira.com/browse/WEBDEV-4200`
=> Resize 2up prefetch update

src/js/BookReader.js, src/js/BookReader/Mode2Up.js, tests/BookReader/Mode2Up.test.js
we are doing our best to cancel any pending requests
we are saving up to 50 images that 2up & thumbnail can use
we reuse images often, and resize as much as possible.
load a book with network tab on..
flip through pages,
toggle side menu,
toggle fullscreen,
— if current image scale is better or equal, we keep the image
thumbnail view: go to thumbnail from 2up, remember your page -> inspect that page in thumbnail view, it should be the same URL + check in network tab for that URL - no secondary image request gets made
https://webarchive.jira.com/browse/WEBDEV-4255
=> More image caching

src/js/BookReader.js, src/js/BookReader/ImageCache.js, src/js/BookReader/Mode2Up.js, tests/BookReader/ImageCache.test.js, tests/BookReader/Mode2Up.test.js
+ use in 2up - book draw & page flip
ImageCache sits at the bottom of an image request and manages the appropriate conditions on whether or not to fetch image:
- if image has not been fetched before => fetch, store, return
- if image requested has been fetched but the requested scale is better => bust cache, fetch, store, return
- if image requested & stored image has has an equal or "better" scale factor => return stored image
use in 2up mode:
- actual prefetch of an image is now thoroughly decoupled with the DOM draw
- `prepareTwoPageView` can now always provide the freshest page containers around an image
- flipping right & left no longer trumps the previous `br.prefetchedImgs` store when making call to prefetch next images
- book of irregular page size - you can scroll horizontally to …
=> ImageCache & 2up's integration

BookReaderDemo/bookreader-template-bundle.js, BookReaderDemo/demo-internetarchive.html, package.json, src/BookReaderTemplate/BookReaderTemplate.js, src/js/plugins/plugin.item_nav.js, webpack.config.js
This fixes the Webpack build phase. It was failing because of `type: module`, but we don't need this for es modules.
This also adds a build script to build a demo module for of the `bookreader-template` component
=> Add support for building the module for demo and fix webpack

src/js/BookReader.js, src/js/BookReader/ImageCache.js, src/js/BookReader/Mode2Up.js, src/js/BookReader/options.js, src/js/BookReader/utils.js, tests/BookReader/ImageCache.test.js, tests/BookReader/utils.test.js
- uses image cache dictionary to use best fetched image url
- value can be seen during the following actions:
- switching modes from 2up -> thumbnail/gallery
- browser width resize while in thumbnail/gallery mode
- scrolling quickly up & down through thumbnail/gallery mode
- reduces "row buffer" on draw
- image reducer is factor of 2, to reduce calls with odd number factors that aren't respected by image service
- no longer saving image element
- serves image element on the fly
- `imageLoaded` checks against given index & reducer
- unit tests
- new promise based sleep function
- unit test
- this accounts for books of irregular widths, ensuring that:
- a spread can be scrolled horizontally if needed
- a spread that doesn't need to be scrolled doesn't have a scrollable container
=> Thumbnail draw with prefetched images ++

src/js/BookReader.js, src/js/BookReader/BookModel.js, src/js/BookReader/Mode1Up.js, src/js/BookReader/Mode2Up.js, src/js/BookReader/options.js, src/js/BookReader/utils.js, tests/BookReader/Mode1Up.test.js, tests/e2e/helpers/base.js, tests/e2e/viewmode.test.js, tests/plugins/tts/AbstractTTSEngine.test.js
Add support for books/things scanned at multiple PPIs.
TODO:
Review App: https://ia-petabox-drini.archive.org/details/lp_broken-hearted-ill-wander_dolores-keane-john-faulkner
Known issues:
- Things still start out to small on IA, but that was a pre-existing issue, so not dealing with it as part of this, cause this change is large enough as is :)
| Before | After |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/6251786/111390620-69498700-8689-11eb-8e05-e1317ccec91a.png) https://lucid-poitras-9a1249.netlify.app/bookreaderdemo/demo-internetarchive?ocaid=lp_broken-hearted-ill-wander_dolores-keane-john-faulkner#page/n1/mode/1up | ![image](https://user-images.githubusercontent.com/6251786/111390653-78c8d000-8689-11eb-8375-4dc502baa191.png) …
=> Mode1Up DPI awareness

src/BookNavigator/BookNavigator.js
Remove loading indicator after JSIA init
The slow part of loading is the loading of the BR JSIA ; once that's done we're good. This also fixes an issue with requests being made for very tiny images during load.
Note there is a petabox-side change which delays the `br.init()` to remove the small image requests; it seems like otherwise it's happening too soon.
=> Fix: Load order + rm tiny image requests during loading

src/js/BookReader/Mode2Up.js
🤦‍♂️ Was getting lots of console.warns, which I think will flood sentry.
Tested that the `pageContainers` object gets cleared when jumping large ranges.
=> Remove reference to deprecated pruneUnused

src/js/BookReader.js
Was getting a "e.ui.mouse.prototype" is undefined error (or something)
on iOS (tested 8-12, errored on all), preventing me from testing there.
Turns out we need some more pieces from jquery-ui for touch-punch.
Oooh, this also fixed it on FF Mobile!
Build file went up ~5kb.
Testing: Confirm https://deploy-preview-731--lucid-poitras-9a1249.netlify.app/bookreaderdemo/demo-internetarchive?ocaid=theworksofplato01platiala working on iOS 11 .
=> Fix BookReader erroring on older iOS

src/BookNavigator/bookmarks/bookmarks-loginCTA.js, src/BookNavigator/bookmarks/bookmarks-provider.js, src/BookNavigator/bookmarks/ia-bookmarks.js
Adding a.o bean counter for bookmarks login clicks
+ update demo to pass proper `baseHost` param
Testing:
go to staging server using incognito browser & open network tab -> open side menu -> go to bookmarks -> login -> confirm no sampling event firing
=> bookmarks login add a.o no-sampling ping & update ia demo basehost param

src/BookReader.js
Problem:
During 1up mode, when toggling fullscreen, booknav's resize caller is breaking fullscreen animation mid-way through.  Result is Black page - the actual page is there, just unseen
Solution:
set animation flags during fullscreen animation
Tech note: - animation sets `opacity` directly to `BRContainer` and gradually changes it from 0 - 1. In order to ensure that there isn't a race condition, we need to set `this.animating` flag at the beginning & unset at the end of the animation.
=> Fullscreen toggle - wrap in animation flags so BookNav knows that core is animating

.github/workflows/node.js.yml
Shaves off ~30 seconds off CI.
First time: npm i took 37s (4m29 total)
Second time: npm i took 10s (3m6 total)
=> Add node_modules caching to GitHub Actions

src/BookReader/Navbar/Navbar.js, tests/BookReader/Navbar/Navbar.test.js
Make the mobile scroller a little less cramped.
=> Remove word "Page" from navbar

src/BookNavigator/BookNavigator.js, src/BookNavigator/volumes/volumes-provider.js, src/BookNavigator/volumes/volumes.js, src/ItemNavigator/providers/sharing.js, tests/karma/BookNavigator/sharing/sharing-provider.test.js
1. go to: https://www-isa2.archive.org/details/tijdschrift-de-as/de_AS_104-105%20-%20België/page/19/mode/2up
2. open multiple-files panel using shortcut -> menu opens & active file can be seen in view. 👍 
3. scroll to any file & select => page refreshes to display the new subfile
4. open multiple-files panel using shortcut -> menu opens & active file can be seen in view. 👍 
5. open sharing panel -> share file with your chosen provider -> note that the url has `/details/<id>/<encodedFilePath>`
6. copy & paste that url in a new window -> takes you to /details page with subfile.
- **Scroll active file into view at first panel open - helps when list is long**
- opting for first update as of now so that we do not conflict with list sort behavior
- UI issue: `scrollIntoView` is borking the menu …
=> sharing panel - add subfile awareness

src/BookNavigator/BookNavigator.js, src/BookNavigator/assets/icon_sort_asc.js, src/BookNavigator/assets/icon_sort_ascending.js, src/BookNavigator/assets/icon_sort_desc.js, src/BookNavigator/assets/icon_sort_descending.js, src/BookNavigator/volumes/volumes-provider.js, src/BookNavigator/volumes/volumes.js, tests/karma/BookNavigator/book-navigator.test.js, tests/karma/BookNavigator/volumes/volumes-provider.test.js
- files sorted by ascending title: AZ w/ UP arrow
- files sorted by descending title: AZ w/ DOWN arrow
=> Subfiles sort updates: sort icons, labelling, open on load

src/BookReader.js, src/BookReader/utils.js, tests/BookReader/utils.test.js
Closes #371 ; Closes #673 ; Closes WEBDEV-4107
Breaking change: Remove public method `BookReader.prototype.keyboardNavigationIsDisabled`
To test:
Go to one of the demos.
Run this JS:
```js
customElements.define('test-element', class extends HTMLElement {
constructor() {
super();
this.attachShadow({mode: 'open'});
this.shadowRoot.append(document.createElement('input'));
}
});
$(document.body).prepend($(`<test-element/>`));
```
Type in the added input.
=> Fix keyboard shortcuts interferring with input fields [BC]

src/BookNavigator/search/search-provider.js, src/BookReader.js, src/BookReader/Mode1Up.js, src/BookReader/Mode2Up.js, src/BookReader/PageContainer.js, src/css/_BRpages.scss, src/css/_BRsearch.scss, src/css/_TextSelection.scss, src/plugins/plugin.text_selection.js, src/plugins/search/plugin.search.js, src/plugins/search/view.js, src/plugins/tts/plugin.tts.js, tests/BookReader/PageContainer.test.js, tests/e2e/helpers/desktopSearch.js, tests/e2e/helpers/mobileSearch.js, tests/plugins/plugin.text_selection.test.js
Now we don't have to manually update their positions, since they just scale like images! Pre-requisite refactor for Pinch zoom.
Notes:
- ~This does increase the memory footprint a bit :/ Since page containers could be kept around for a potentially long time, and precached/cached, I needed a way to make sure all layers were up-to-date.~
- ~Actually, it introduces a memory leak :/~
- Both fixed!
=> Convert search/tts hilites into an SVG layer

src/BookReader/utils.js, tests/BookReader/utils.test.js
To test:
Go to one of the demos.
Run this JS:
```js
customElements.define('test-element', class extends HTMLElement {
constructor() {
super();
this.attachShadow({mode: 'open'});
this.shadowRoot.append(document.createElement('textarea'));
}
});
$(document.body).prepend($(`<test-element/>`));
```
Type in the added input.
=> Textareas should also be keyboard shortcut deadzones

BookReaderDemo/demo-internetarchive.html
WEBDEV-4950
This preps for multiple file support in demo
Testing:
- go to [IA demo page](https://deploy-preview-898--lucid-poitras-9a1249.netlify.app/bookreaderdemo/demo-internetarchive?ocaid=theworksofplato01platiala)
- ✅  note that top title bar is gone from demo
OLD: 
NEW:
=> Demo: update IA Demo so that it does not use the automagic script loader

src/plugins/tts/FestivalTTSEngine.js
Resolves Issue #899 
Added the `//eslint-disable-line` comment to line 26 so that it disables all warnings for that particular line only.
Kindly review @cdrini
=> Resolved eslint on $.browser

src/plugins/search/plugin.search.js
Problem: jQuery AJAX JSONP calls are no cache by default.
Even if search endpoint returns cache header, there is a random string in URL that prevents browser to cache request.
Task: set `cache: true` in AJAX config
WEBDEV-4972
=> search inside request: turn on cache for request (removes random string in url)

BookReaderDemo/demo-internetarchive.html, package-lock.json, package.json, src/BookNavigator/book-navigator.js, src/ia-bookreader/ia-bookreader.js
updates to support flattened, shadydom 
testing: go to https://deploy-preview-919--lucid-poitras-9a1249.netlify.app/bookreaderdemo/demo-internetarchive?ocaid=theworksofplato01platiala -> works ✅ 
using https://github.com/internetarchive/iaux-item-navigator/pull/5
=> Shady dom css shifts

src/plugins/tts/PageChunk.js
Some books mis-OCR a dangling hyphen as a ¬ (mathematical not sign) . Since in math the not sign should not appear followed by a space, we think we can safely assume this should be replaced.
Reported on twitter: https://twitter.com/neurdy/status/1484567701666156546
Tested with the word "Between" on the right page here, in Chrome: https://archive.org/details/contestedknowled0000seid_x2i5/page/230/mode/2up
=> Update hyphen stitching regex to include dangling "¬" (not signs)

BookReaderDemo/IADemoBr.js, BookReaderDemo/demo-internetarchive.html, BookReaderDemo/ia-multiple-volumes-manifest.js, src/BookNavigator/book-navigator.js, src/ia-bookreader/ia-bookreader.js, tests/karma/BookNavigator/book-navigator.test.js
Fixes dom check to toggle side menu
+ new demo button -> draw a multiple files book dynamically to show side menu (does not fully work as it is not tied to the XHR manifest call, but a quick click to see side menu)
to test demo, go to: https://deploy-preview-931--lucid-poitras-9a1249.netlify.app/bookreaderdemo/demo-internetarchive?ocaid=theworksofplato01platiala# 
- > scroll down & click on "Multiple Books" -> bookreader dynamically loads `SubBookTest` with mulitiple files pane open
=> Pop open side menu

src/BookNavigator/book-navigator.js, src/plugins/url/UrlPlugin.js, tests/jest/plugins/url/UrlPlugin.test.js, tests/karma/BookNavigator/book-navigator.test.js
Problem: The Shared Resize observer loads after the side menu providers have, thus not conveying proper browser dimensions to those listening for it.
Solution: re-hydrate menus.
Problem: when primary url ends with trailing slash, it appends it, thus adding `//` to url. cannot properly reload page.
Solution: check for `//`
=> Shared RO late load & Url Plugin double slash fix

src/plugins/tts/plugin.tts.js
Closes #915 / [WEBDEV-5051](https://webarchive.jira.com/browse/WEBDEV-5051)
Tested in FF, Chrome latest win 10
- TTS follows along but not super great in non-fullscreen 2up BR
- TTS stays in center of screen in 1up, FS or no
- Trigger TTS, jump to distant page, goes back normally in 1up/2up
- Thumb does same weird thing it always did.
=> Fix ReadAloud not scrolling along the text

.github/workflows/npm-publish.yml
It's been broken for a really long time, and no one uses it, so let's not waste computer cycles building it, eh?
=> Remove package publishing to github

src/plugins/search/plugin.search.js, src/plugins/search/view.js, tests/e2e/base.test.js, tests/e2e/helpers/desktopSearch.js, tests/e2e/models/Navigation.js, tests/e2e/rightToLeft.test.js, tests/e2e/viewmode.test.js
Re-enable + fix testcafe search tests for shadow dom.
- testcafe was erroring with `BRSearchInProgress` undefined
- Reaching into shadow DOM 😬 We probably want to setup a proper pattern for doing this, probably ok for now?
- dom.searchNavigation was null in github CI; but worked locally for me
=> Fix broken testcafe search tests

.github/workflows/node.js.yml
Saves about ~45s on CI (~5.2min → ~4.5min, sample size ~2). A big chunk is probably from fully skipping `npm install` when we have a `node_modules` cache hit. Then we also parallelize e2e tests with unit test running.
Sample run graph: https://github.com/internetarchive/bookreader/actions/runs/1959466247
Before:
After:
=> Try splitting node workflow into different jobs

renovate.json
Our usage of it is super basic, so it's unlikely to ever cause an issue
=> Auto-update dev dependencies for minor/patch

codecov.yml
Codecov is constantly failing for small changes -- oftentimes incorrectly. Let's add some leniency here ; if your change is very tiny, it's ok if it causes a coverage decrease.
=> Allow small drops in codecov coverage (< 0.5%)

renovate.json
This will place all icon updates in one PR, but not auto-merge. Since there are no tests that really cover whether the icons are working correctly, I think it might be best to have these require manual verification/merge.
=> Group @internetarchive icon updates

renovate.json
These repos often contain web components which get registered globally, so we would rather have ranges with these than pinned dependencies
=> Use range strategy bump for @internetarchive

src/BookReader/Mode1UpLit.js, src/BookReader/Mode2Up.js, src/BookReader/ModeSmoothZoom.js, src/BookReader/PageContainer.js, src/BookReader/utils/ScrollClassAdder.js, src/css/_TextSelection.scss, tests/jest/BookReader/PageContainer.test.js, tests/jest/BookReader/utils/ScrollClassAdder.test.js
This didn't have a big impact on experience anecdotally, but I imagine it's probably good. Note the elements are no longer flashing in the devtools.
| Before | After |
| -- | -- |
| <video src="https://user-images.githubusercontent.com/6251786/158461482-e53e70ce-a325-4271-9266-cf1841f0956f.mp4"> | <video src="https://user-images.githubusercontent.com/6251786/158461668-1f7a0fce-4c99-494d-aab4-68c1a47c1e08.mp4"> |
This had a big impact on books with large text layers!
https://user-images.githubusercontent.com/6251786/158468209-a580f8d0-c379-4387-a7d8-5c23da8079b9.mp4
Reduces "sticky" feeling when starting scroll/zoom. Note before/after here is relative to Perf improvement 2.
https://user-images.githubusercontent.com/6251786/158490805-cefd5993-1b52-41e5-bec1-078fcb694de5.mp4
- Before: …
=> Performance improvements to scroll/zooming when text layer is larger

src/BookNavigator/search/search-provider.js, src/BookReader.js, src/BookReader/PageContainer.js, src/BookReader/utils.js, src/css/_BRsearch.scss, src/plugins/search/plugin.search.js, src/plugins/search/view.js, src/plugins/tts/FestivalTTSEngine.js, src/plugins/tts/WebTTSEngine.js, src/plugins/tts/utils.js, tests/jest/BookReader/BookReaderPublicFunctions.test.js, tests/jest/BookReader/PageContainer.test.js, tests/jest/BookReader/utils.test.js, tests/jest/plugins/tts/utils.test.js, tests/karma/BookNavigator/search/search-provider.test.js
Examples:
- https://deploy-preview-998--lucid-poitras-9a1249.netlify.app/bookreaderdemo/demo-internetarchive?ocaid=goody#page/8/mode/1up/search/margery
- https://deploy-preview-998--lucid-poitras-9a1249.netlify.app/bookreaderdemo/demo-internetarchive?ocaid=sim_weekly-recorder-a-news-paper_1819-12-09_6_17#mode/1up/search/god
Outstanding:
- PUNT: On mobile search panel no longer closing for some reason after clicking
- Apparently pre-existing issue; not related to changes here
- PUNT: Not scrolling into view on initial search
- It usually is? Some books seem to have `options.goToFirst` set to false :/ (like https://archive.org/details/sim_los-angeles-times_1989-04-30_parsed/sim_los-angeles-times_1989-04-30_2/page/n88/mode/1up?q=ibm )
Future fixes:
- #1011 
- Zoom in to ensure selected …
=> Feature: Some visual bounce to make search highlight more noticeable on click

renovate.json
Any errors will very likely be caught by CI, so automerge! This will update things like: https://github.com/internetarchive/bookreader/blob/3111b955903a1e2bff5a1f3a8112f76b96348a2f/.github/workflows/npm-publish.yml#L14
- `matchDataSources` will match all the github action deps not using any pattern; just get all of 'em!
- `groupName` causes the updates to only create one PR and get updated together
- `automerge` ... auto merges!
=> Bundle/auto-merge GitHub actions updates

renovate.json
This is getting a little noisy, and causing netlify to struggle with all the PRs. Limit to monthly for non-IA package updates.
=> Limit non-ia dep updates to monthly

src/css/_controls.scss, src/plugins/tts/plugin.tts.js
**Changes:** 
- add `renderVoiceOption()` which takes in `language` parameter, where two groups of language is passed, _english(en)_ and _non-english_
- `bookLanguages` and `otherLanguages` stores filtered out grouping of languages in a sorted ordered
- `voicesMenu` appends grouping of `english` and `non-english` languages where `<optgroup` is introduced
**Test and Checks** 
- Ran eslint and nothing seemed to break style wise
**Screenshot:** 
**Fixes:** 
Fixes #1055
=> add helper function, <optgroup> and sort function

src/BookNavigator/search/search-provider.js, src/BookNavigator/search/search-results.js, src/plugins/search/plugin.search.js, tests/jest/BookNavigator/search/search-provider.test.js, tests/jest/BookNavigator/search/search-results.test.js
This PR removes `q=<term>` query param when search is cancelled or when search menu input is cleared
=> keep  url param dynamic with patron's search request

src/BookReader/Mode2Up.js, tests/jest/BookReader/Mode2Up.test.js
This issue affects right-to-left page flipping via the "next page" button in 2up mode. It mainly appears to affect texts with an even number of pages where the first and last pages present on their own.
If the new left page remains left-positioned upon flipping to the next page, its animation unfolds in the wrong direction. Ensuring before the animation that it is right-positioned at the center prevents this issue.
This PR should also address https://github.com/internetarchive/bookreader/issues/173 which appears to have the same root cause.
Preview app: https://deploy-preview-1077--lucid-poitras-9a1249.netlify.app/bookreaderdemo/demo-internetarchive?ocaid=CIA-RDP05S00620R000300830010-7
- Flip through all the pages of the given text until the end (e.g., with the right arrow key, clicking …
=> Fix leaf positioning during rtl flip anim

src/BookReader/Mode2Up.js
Large books with leaf edges had weird page offsets/shifts during the
page flip animation as a result of the previous anim fix.
This change ensures the page is positioned correctly throughout the
animation regardless of whether leaf edges are present.
In [my earlier fix for page flipping animations](https://github.com/internetarchive/bookreader/pull/1077), I applied an incorrect offset to the left page as it flips leftward, which is noticeable mainly in longer books that have clickable leaf edges. This results in some undesirable page shifting upon the animations completing and everything snapping into place:
The pages should animate to their correctly-offset position smoothly and not have any jarring snaps at the end when flipping right through the book.
Code-wise, this is just a quick …
=> Fix positioning during page flip for large books

BookReaderDemo/demo-internetarchive.html, src/BookNavigator/book-navigator.js, tests/jest/BookNavigator/book-navigator.test.js
Restricted book https://deploy-preview-1080--lucid-poitras-9a1249.netlify.app/bookreaderdemo/demo-internetarchive?ocaid=sim_gramophone_1926-01_3_8 
- once book loads, open dev console
- ✅ right click on image => console.log output notes `~~~ NO SAMPLE EVENT CALLED:  ` + GA event details
-   `{category: 'BookReader', action: 'contextmenu-restricted', label: 'BRscreen'}`
- ✅ NO context menu shows up to allow for image download
- ✅ works in 2up, 1up, thumb
Unrestricted book https://deploy-preview-1080--lucid-poitras-9a1249.netlify.app/bookreaderdemo/demo-internetarchive?ocaid=goody#page/n22/mode/2up 
- ✅ right click on image => console.log output notes `~~~ NO SAMPLE EVENT CALLED:  ` + GA event details
- ✅ YES context menu shows up to allow for image download
- ✅ works in 2up, 1up, thumb
=> Disable contextmenu on restricted books

src/BookNavigator/search/a-search-result.js, tests/jest/BookNavigator/search/search-results.test.js
**Problem:** Search results are rendered using the `unsafeHTML` directive, which allows HTML tags present in the underlying document to be injected into the DOM when they appear in search results. This creates an XSS vulnerability when, e.g., the underlying document contains `<script>` tags that will be executed upon rendering the search results.
This PR ensures that search results are inserted into the DOM as raw text, with the only active markup present being the `<mark>` tags added to highlight the search keywords.
=> WEBDEV-5491 Ensure search results are sanitized

src/plugins/search/view.js, tests/jest/plugins/search/plugin.search.view.test.js
Follow-up to #1088 -- unescaped search results appear in the footer bar as well. This PR ensures they are escaped before being inserted into the DOM.
**Testing:** Visit https://deploy-preview-1091--lucid-poitras-9a1249.netlify.app/bookreaderdemo/demo-internetarchive?ocaid=book-reader-test-1234#mode/1up/search/searching and verify that no browser alert occurs (initially or upon performing different searches).
=> Escape search results being shown in the footer bar

BookReaderDemo/IADemoBr.js, src/BookNavigator/book-navigator.js, src/BookNavigator/volumes/volumes-provider.js, tests/jest/BookNavigator/book-navigator.test.js
Calls transferred to 1% sample bucket:
- on load, signal when book is restricted
- volume sorting when viewing a multi-volume book
=> ia analytics, move to 1% sampled bucket

src/BookNavigator/bookmarks/ia-bookmarks.js, src/BookReader.js, src/BookReader/BookModel.js, src/BookReader/Mode1UpLit.js, src/BookReader/Mode2Up.js, src/BookReader/ModeThumb.js, src/BookReader/Navbar/Navbar.js, src/BookReader/Toolbar/Toolbar.js, src/plugins/plugin.autoplay.js, src/plugins/plugin.chapters.js, src/plugins/search/plugin.search.js, src/plugins/search/view.js, src/plugins/tts/plugin.tts.js, tests/jest/BookReader.test.js, tests/jest/BookReader/BookModel.test.js, tests/jest/BookReader/BookReaderPublicFunctions.test.js, tests/jest/BookReader/Mode1UpLit.test.js, tests/jest/BookReader/Mode2Up.test.js, tests/jest/plugins/plugin.autoplay.test.js, tests/jest/plugins/plugin.chapters.test.js
These were added as part of the v5 transition to avoid breaking changes. Let's get rid of as many as possible.
A few are left because they are used in petabox, or because they were overriden in plugins.
=> Remove most class shims + v5 BR deprecations

src/plugins/tts/WebTTSEngine.js, tests/jest/plugins/tts/WebTTSEngine.test.js
iOS 16 seems to somehow not show the default OS voice in the menu (Usually Samantha or Samantha Enhanced). So include an options specifically on these devices for the system default. This sets the voice to `null` under the hood when the speech utterance is made.
=> Fix default iOS voice missing from menu

netlify.toml, src/css/_TextSelection.scss, src/plugins/plugin.text_selection.js
CORS endpoint isn't enabled for protected endpoints, so need to use JSONP.
Note in a completely unrelated change I added cors support to netlify so we can pull from the netlify build from archive.org review apps!
=> Add jsonp support to textsel fetches + Netlify CORS support

src/BookReader/Mode1Up.js, src/BookReader/Mode1UpLit.js
It seems like a scroll event isn't fired when we set scrollTop before it's rendered. This is causing black screens and the url to change from eg `/page/n53/mode/1up` to `/page/nundefined/mode/1up`.
Testing:
- https://deploy-preview-1177--lucid-poitras-9a1249.netlify.app/bookreaderdemo/demo-internetarchive?ocaid=pinehurstestates.preplat.1997 renders correctly (note master, removing `deploy-preview-1177--`, black screens)
=> Fix page/nundefined errors causing blackscreen

src/BookReader/Mode2UpLit.js
Closes #1189
The UX design here had the book scale upto but not surpass its real-world size on initial page load. But there are too many books missing PPI entirely or having incorrect PPIs, so removing that check.
https://deploy-preview-1197--lucid-poitras-9a1249.netlify.app/bookreaderdemo/demo-internetarchive?ocaid=mss-25-rock-rule#mode/2up
=> Don't limit autoFit zoom to real world size

src/BookNavigator/search/search-results.js, src/BookReader/utils.js, src/css/_BRnav.scss, src/css/_BRsearch.scss, src/plugins/search/plugin.search.js, src/plugins/search/utils.js, src/plugins/search/view.js, tests/e2e/helpers/desktopSearch.js, tests/jest/BookNavigator/search/search-results.test.js, tests/jest/BookReader/utils.test.js, tests/jest/plugins/search/plugin.search.test.js, tests/jest/plugins/search/plugin.search.view.test.js, tests/jest/plugins/search/utils.js, tests/jest/plugins/search/utils.test.js
Also closes #1188 
We will be switching from {{{/}}} to a less common string, since issues arise when the original OCR contains eg `{{{`.
Changes:
- New options for `searchInsidePreTag: {{{`, `searchInsidePostTag: }}}`
- DRY where a search is rendered
- Small style tweaks to search hover cards
- Also new option `searchInsideProtocol` for #1188 .
=> Search inside option for {{{/}}} + http support

package-lock.json, package.json
This was a strange issue.
So core-js in commit https://github.com/zloirock/core-js/commit/25e93739aa8623a47526cc65f2d8e5d68bd3b107 changed some code from `typeof global.process` to `typeof process`. Unfortunately this resulted in some part of esm.sh when transpiling for deno to think that the node library `process` needed to be imported. You can see it on the first line here: https://esm.sh/v130/@internetarchive/bookreader@5.0.0-64/deno/BookReader/BookReader.js . 
So for now rollback core-js to the previous version before this change was introduced. Not sure where the bug lies here ; whether this is an issue with core-js or esm.sh . But this is the quickest way for us to unblock our deploy flow to archive.org
Created an issue on core-js at least: …
=> Downgrade core-js to fix esm.sh build issue

BookReaderDemo/toggle_controls.html, src/BookReader/Navbar/Navbar.js, src/css/_BRnav.scss, src/css/_controls.scss, src/plugins/tts/plugin.tts.js
- Disable them on touch screens ; they show up at an awkward time and can be difficult to dismiss
- On IA, the tooltips were there (potentially blocking other UI elements) but opacity: 0 due to a CSS classname clash with `.tooltip`. Fix that.
=> Disable tooltips on touchscreens + fix on IA

src/BookReader/Mode1Up.js, src/BookReader/Mode1UpLit.js
Closes #1130 .
Also fixes runaway scroll when going FS on mobile from 2up.
| Before on page load | After on page load |
| --- | -- |
| ![image](https://github.com/internetarchive/bookreader/assets/6251786/b24a4283-4e63-451c-ada9-8640594dc13a) | ![image](https://github.com/internetarchive/bookreader/assets/6251786/e1c8f9f2-1f10-46ce-aeda-535cf6a48c0f) |
Tested on:
- Windows/FF
- Windows/Chrome
- Windows/Edge
- Android/FF
- Android/Chrome
- Android/Edge
- Android/Samsung Internet
- iPad 16.6/Safari
- iPad 16.6/Chrome
- Mac/Safari 16.5 (BS)
- iPhone 14/Safari
=> Fix 1up zoom wrong on start/entering fs

src/plugins/tts/AbstractTTSEngine.js, tests/jest/plugins/tts/AbstractTTSEngine.test.js
Closes #1131 
TTS voice selection is stored after user selects from voice menu. On load, the last selected voice will attempt to be selected from localStorage and loaded as the active voice. If no voice is stored, the default will be selected.
Voice is stored under the localStorage key 'playback-voice'.
=> Store selected TTS voice in localStorage

src/BookReader/utils/SelectionObserver.js, tests/jest/BookReader/utils/SelectionObserver.test.js
Fix common sentry error. It doesn't impact users in any way, but just noisy. It errors when there's a text selection outside the BR!
Tested text selection mode changes still work on Win + FF/Chrome; iPad
=> Fix SelectionObserver firing for any element

.gitignore
Use this to store helpful env variables like browserstack keys. Gitiginore that.
=> Gitignore .env file

src/BookNavigator/book-navigator.js, src/plugins/plugin.chapters.js, tests/jest/BookNavigator/book-navigator.test.js, tests/jest/plugins/plugin.chapters.test.js
Testing:
- goto: https://deploy-preview-1289--lucid-poitras-9a1249.netlify.app/bookreaderdemo/demo-internetarchive?ocaid=adventureofsherl0000unse
- check if Table Of Contents icon is present in the sidebar menu
- then check other books without ToC like: https://deploy-preview-1289--lucid-poitras-9a1249.netlify.app/bookreaderdemo/demo-internetarchive?ocaid=goody
- the ToC icon should not be present in the page/book without ToC
=> Add ToC icon display if enableChaptersPlugin

src/BookNavigator/book-navigator.js
This causes icons to "jump" when toggling between an side panel & shortcuts view
- incorrect:
- open side panel, downloads is below bookmarks, above visual adjustments
- Click demo option "Toggle Logged In View" -> bookmarks panel changes to from Log in button to add a bookmark
- add a bookmark (no XHR POST happens, just client side UI available)
- Toggle side panel -> ✅ Bookmark Shortcut icon shows -> open side panel -> ✅ shortcut icons match open side panel icons & Downloads is before visual adjustments
-
=> side panels - show downloads before visual adjustments

src/BookNavigator/visual-adjustments/visual-adjustments-provider.js, src/BookNavigator/visual-adjustments/visual-adjustments.js, tests/jest/BookNavigator/visual-adjustments.test.js
The visual adjustment text in the side panel is currently grammatically inconsistent, which can make it a bit confusing for readers:
Simply rephrase a few of the phrases to make them all consistent:
- “Inverted colors (dark mode)” should read → “Invert colors (dark mode)”
- “Grayscale” should read → “Convert to grayscale”
- “Zoom” should read → “Adjust zoom”
Probably unnecessary, but I also updated the text in `visual-adjustments.test.js` just in case.
1. Go to the [PR bookreader instance](https://deploy-preview-1338--lucid-poitras-9a1249.netlify.app/bookreaderdemo/demo-internetarchive?ocaid=adventureofsherl0000unse#page/28/mode/2up)
2. Navigate to the Visual Adjustments in the side panel
3. Confirm that they now read:
- Adjust brightness
- Adjust contrast
- Invert colors (dark mode)
- …
=> Rephrase visual adjustment text to improve consistency

.github/workflows/node.js.yml
There don't appear to be any breaking [changes between v3 and v4 as of writing](https://github.com/actions/cache/releases).
Fixes this warning:
> The following actions use a deprecated Node.js version and will be forced to run on node20: actions/cache@v3. For more info: https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/
https://github.com/internetarchive/bookreader/actions/runs/10930025193
=> Bump cache action to v4

BookReaderDemo/IADemoBr.js, src/plugins/search/plugin.search.js, src/plugins/search/view.js
Closes #1344
QA: https://deploy-preview-1345--lucid-poitras-9a1249.netlify.app/bookreaderdemo/demo-internetarchive?ocaid=cu31924009344999&options.showToolbar=true
Note the `options.showToolbar=true` option; that enables the code path that caused this to error
=> Fix Toolbar requiring SearchView.init having already been called

src/BookNavigator/downloads/downloads.js
Currently, our "Install Thorium" link takes you to a more general [about page](https://www.edrlab.org/software/thorium-reader/). To avoid patron confusion, we should instead link to their new [download page](https://thorium.edrlab.org/).
=> WEBDEV-7113 Switch to new Thorium URL

tests/e2e/autoplay.test.js, tests/e2e/helpers/mockSearch.js
These were broken when we switched from JSONP requests to JSON requests as part of the CSP migration.
=> Fix failing e2e tests

src/BookReader.js, src/BookReader/Mode2UpLit.js, src/BookReader/options.js, src/BookReader/utils.js, src/BookReaderPlugin.js, src/plugins/plugin.autoplay.js, src/plugins/tts/plugin.tts.js, src/plugins/url/plugin.url.js, tests/e2e/autoplay.test.js, tests/jest/BookReader/utils.test.js, tests/jest/plugins/plugin.autoplay.test.js
Testing:
* ✅ autoflip works https://deploy-preview-1374--lucid-poitras-9a1249.netlify.app/bookreaderdemo/demo-internetarchive?ocaid=theworksofplato01platiala&autoflip=1
Breaking changes:
* Moves the root autoplay bookreader methods/fields `autoToggle`, `autoTimer`, `autoStop` to `br._plugins.autoplay` as `toggle`, `timer`, `stop`
* Moves the root autoplay options `flipDelay`, `enableAutoPlayPlugin` out of the root options to `options.plugins.autoplay` as `flipDelay` and `enabled`.
New features:
* Adds new option for autoplay plugin, `urlParams`, defaulting to true. When true, `autoflip=1`, `flipSpeed=<number>` and `flipDelay=<number>` will be read from the url to configure the autoplay plugin.
=> Migrate AutoplayPlugin to BookReaderPlugin

src/BookReader.js, src/BookReader/options.js, src/plugins/plugin.resume.js, tests/e2e/helpers/base.js, tests/jest/BookReader.test.js, tests/jest/plugins/plugin.resume.test.js
Blocked by #1374 , so ignore the autoplay files in this diff.
Testing:
1. Go to the netlify review app https://deploy-preview-1375--lucid-poitras-9a1249.netlify.app/bookreaderdemo/demo-internetarchive?ocaid=theworksofplato01platiala
2. Go to a page
3. Remove the `#...` fragment from the url and reload the page
4. ✅ Should be sent back to the same page
Breaking changes:
- `BookReader#getResumeValue()` moved to `BookReader._plugins.resume.getResumeValue()`. Similarly for `getCookiePath`, and `updateResumeValue` .
- The option `enablePageResume: bool` has been renamed to `plugins.resume.enabled: bool`
- The option `resumeCookiePath: string` has been renamed to `plugins.resume.cookiePath: string`
=>  Migrate ResumePlugin to BookReaderPlugin

codecov.yml, src/BookReader.js, src/BookReader/options.js, src/BookReaderPlugin.js, src/plugins/tts/AbstractTTSEngine.js, src/plugins/tts/PageChunk.js, src/plugins/tts/PageChunkIterator.js, src/plugins/tts/plugin.tts.js, src/util/strings.js
Blocked by #1374 , so ignore the autoplay files in this diff
Breaking Changes:
* All root-level BookReader tts methods/fields, eg `BookReader#ttsToggle`, `BookReader#ttsScrollToChunk`, `BookReader#ttsStart`, etc, have all been moved to e.g. `br._plugins.tts.toggle`. That is they are now on the `TtsPlugin` class, and no longer have the `tts` as in `ttsStart`.
* The option `enableTtsPlugin` has been renamed to `plugins.tts.enabled`
* The options `server` and `bookPath` have been replaced with `pageChunkUrl` StringWithVars. This makes the page chunk URL configurable for other clients.
=>  Migrate TtsPlugin to BookReaderPlugin

src/BookReader.js, src/BookReader/options.js, src/plugins/plugin.iiif.js
- Move the plugin setup calls further up in the setup method, so that the `IiifPlugin` can modify/set the data object
- No breaking changes on this one since it was already in a more modern format
Confirm IIIF demos both still work:
- https://deploy-preview-1380--lucid-poitras-9a1249.netlify.app/bookreaderdemo/demo-iiif#page/34/mode/2up
- https://deploy-preview-1380--lucid-poitras-9a1249.netlify.app/bookreaderdemo/demo-iiif?manifest=https%3A%2F%2Fiiif.archive.org%2Fiiif%2F3%2Fplatowithenglish04platuoft%2Fmanifest.json
=> Convert IiifPlugin to BookReaderPlugin

src/BookReader.js, src/BookReader/ImageCache.js, src/BookReader/PageContainer.js, src/BookReader/options.js, src/css/_BRpages.scss, tests/jest/BookReader/PageContainer.test.js
For more control when rendering images.
Also improves image caching to avoid creating new `img` tags when not needed, fixing issue with flashing pages in Chrome
=> Add new renderPageURI option + improve image caching

src/BookReader.js, src/BookReader/options.js, src/plugins/plugin.chapters.js, tests/jest/plugins/plugin.chapters.test.js
~Blocked by #1380~
Breaking changes:
* Options moved:
* `options.olHost` → `options.plugins.chapters.olHost`
* `options.enableChaptersPlugin` → `options.plugins.chapters.enabled`
* Note `table_of_contents` _did not_ move; that is still root-level
* All chapters state/methods moved from `BookReader` to `BookReader.plugins.chapters`. Full list:
* `BookReader._chapterInit` has been dissolved
* `BookReader._chaptersRender` → `ChaptersPlugin._render`
* `BookReader._chaptersRenderMarker` → `ChaptersPlugin._renderMarker`
* `BookReader.getOpenLibraryRecord` → `ChaptersPlugin.getOpenLibraryRecord`
* `BookReader._chaptersUpdateCurrent` → `ChaptersPlugin._updateCurrent`
* `BookReader._tocEntries` → `ChaptersPlugin._tocEntries`
* `BookReader._chaptersPanel` → `ChaptersPlugin._chaptersPanel`
=>  Convert ChaptersPlugin to BookReaderPlugin 

src/plugins/plugin.text_selection.js
Closes #1140
Issues:
- Not allowing selection at all on FF Android
- Difficult to test on safari because of #1129
=> Add protected option to text selection plugin

src/plugins/tts/WebTTSEngine.js, src/plugins/tts/utils.js, src/util/browserSniffing.js, tests/jest/plugins/tts/WebTTSEngine.test.js, tests/jest/util/browserSniffing.test.js, tests/jest/utils.js
Closes #184
The chrome auto-pause work around wasn't working correctly, and causing the audio to pause/resume at random moments. Fix the state machine to make sure only one state machine is ever running.
Also fix a bug where Edge was being incorrectly identified as Chrome. It doesn't not have the TTS bug for which we have this workaround.
Tested, no new bugs!
Firefox 136.0 / Windows 10
✔️ Runs
✔️ Can advance and review
✔️ Can change voice
✔️ Can change speed
✔️ Can pause
✔️ Can resume
❌ Shows media session
✔️ Can play while screen off
Microsoft Edge 134.0.0.0 / Windows 10
✔️ Runs
✔️ Can advance and review
✔️ Can change voice
🔵 Runs 15+ seconds non-local voice (skipped)
✔️ Can change speed
✔️ Can pause
✔️ Can resume
✔️ Shows media session
✔️ Can play while screen off
Chrome 134.0.0.0 / …
=> Fix TTS chrome pausing workaround bugs

BookReaderDemo/IADemoBr.js, BookReaderDemo/ia-multiple-volumes-manifest.js, src/BookNavigator/book-navigator.js, src/BookNavigator/search/search-provider.js, src/BookNavigator/sharing.js, src/BookReader.js, src/BookReader/Toolbar/Toolbar.js, src/BookReader/options.js, src/BookReaderPlugin.js, src/plugins/search/plugin.search.js, src/plugins/search/view.js, tests/e2e/helpers/mockSearch.js, tests/jest/BookNavigator/book-navigator.test.js, tests/jest/BookNavigator/search/search-provider.test.js, tests/jest/BookNavigator/sharing/sharing-provider.test.js, tests/jest/BookReader.test.js, tests/jest/plugins/search/plugin.search.test.js, tests/jest/plugins/search/plugin.search.view.test.js, tests/jest/plugins/url/plugin.url.test.js
Breaking changes:
* Search options are now nested under the plugin (eg `searchInsideUrl` → `options.plugins.search.searchInsideUrl`), and mostly longer include the `search` prefix; specifically:
* `searchInsidePreTag`, `searchInsidePostTag` → `options.plugins.search.preTag` and `postTag`
* `searchInsideUrl` is now a `StringWithVars` and supports including `vars` from the root options, e.g. `searchInsideUrl: "https://{{server}}/search_endpoint?q={{query|urlencode}}"` . It also has access to the `preTag` and `postTag` from the options. Note this allows the search inside URL to now be fully customizable from the options, and is no longer hard-coded internally to Internet Archive specific logic. 
* `initialSearchTerm` → `options.plugins.search.initialSearchTerm`
* `searchInsideProtocol` → …
=> Convert SearchPlugin to BookReaderPlugin

src/plugins/search/view.js
Was seeing some warnings in the dev server logs. Since plugins are setup before these fields are saved on the BR object, this needs to be fetched directly from options.
=> Fix search icon being fetched from wrong path

package.json
Confirmed with `npm pack --dry-run` that it is now indeed including BookReader/! Apparently otherwise it ignore .gitignore!
=> Fix BookReader/ build dir missing from npm package!

BookReaderDemo/css/index.css, src/assets/translate/worker.js, src/css/_TextSelection.scss, src/plugins/plugin.text_selection.js, src/plugins/translate/TranslationManager.js, src/plugins/translate/plugin.translate.js, src/util/cache.js, src/util/translationmanager.js
1. Add type docs to properties of TranslatePlugin Class
2. Take translated paragraphs and divide into chunks using '.' as delimiter to show translations as lines to allow for graphics in digital works. 
- Grabs CSS values from existing ```.BRlineElement``` and ```.BRparagraphElement``` to attempt to keep translated text within the bounds of the paragraph text being translated. 
- Currently using overflow-y: auto to let overflow text be visible via scrolling
- font-size property for spans are adjusted to be slightly smaller (5px smaller for now) since text from passages tends to go past the height of the container.
=> [GSoC] Auto-Translate: Add Properties, Show Translations as Lines

src/BookReader.js, src/BookReader/options.js, src/plugins/translate/plugin.translate.js, tests/jest/BookReader.test.js, tests/jest/BookReader/Navbar/Navbar.test.js
Otherwise it is impossible to specify lit `TemplateResult`s as options, because some of their internal methods get flattened out.
This will be necessary in order to show the IA feedback button via the option, otherwise was getting an error when I assigned a lit `TemplateResult`, eg
```
translations: { panelDisclaimerText: html`<ia-feedback-button ...>...</ia-feedback-button>` }
```
Apparently the `html` method returns a `TemplateResult` , which is an object that has a `.strings` field which is an array of strings. However this array has a property `.raw`, and it seems like this is getting stripped by jQuery's default `.extend` method. To avoid it running, I switched to a shallow extend instead of a deep extend, but have to add some exceptions for spots where we _do_ want a deep extend, …
=> Add BookReader.extendOptions method for shallow options merge

package-lock.json, package.json, src/plugins/translate/TranslationManager.js, src/plugins/translate/plugin.translate.js, src/plugins/tts/utils.js
Translation Plugin sidebar menu updated to using feedback from UI/UX meeting
- "From" language -> "Source" language. 
- Source language field/dropdown is not immediately available and is only visible after a user clicks on "Change"
- Add status message in sidebar if "Translate To" and "Source" languages are the same, which hints to why a translation may not work for the page.
- Misc styling
Before
----
After
----
=> Redesign Translation Side Menu
